/** Universal message and content types — shared by LLM, Agent, Server. */

import type { ProviderName } from './provider';

export type Role = 'system' | 'user' | 'assistant' | 'tool';

/** Producer-bound provenance for an assistant turn.
 *
 *  History is portable across providers, but some state is only valid for the
 *  provider that produced it: a server-side conversation id (interaction_id /
 *  response_id) and opaque signatures (Gemini thought-signatures, reasoning
 *  blobs). Anything here MUST be ignored by a different provider — adapters
 *  consume it only when `origin.provider === self`. */
export interface MessageOrigin {
  /** Provider that produced this assistant turn. The gate for cross-provider use. */
  provider: ProviderName;
  /** Model that produced it (for model-bound server-state checks). */
  model?: string;
  /** Server-side conversation id for stateful continuation (interaction_id / response_id). */
  serverStateId?: string;
  /** Opaque provider signatures to echo back (thought-signature, encrypted reasoning). */
  signatures?: unknown;
}

export type ContentPart =
  | TextPart
  | ImagePart
  | DocumentPart
  | AudioPart
  | VideoPart
  | ToolCallPart
  | ToolResultPart
  | ImageOutputPart
  | AudioOutputPart
  | VideoOutputPart;

export interface TextPart {
  type: 'text';
  text: string;
  cache?: boolean;
}

export interface ImagePart {
  type: 'image';
  source: DataSource;
  detail?: 'auto' | 'low' | 'high';
}

export interface DocumentPart {
  type: 'document';
  source: DataSource;
  citations?: boolean;
}

export interface AudioPart {
  type: 'audio';
  source: DataSource;
}

export interface VideoPart {
  type: 'video';
  source: DataSource;
}

export interface ToolCallPart {
  type: 'tool_call';
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  /** Provider-specific metadata (e.g. Google thought signatures). */
  _meta?: Record<string, unknown>;
}

export interface ToolResultPart {
  type: 'tool_result';
  id: string;
  content: string | ContentPart[];
  isError?: boolean;
}

// ─── Media Output Parts (generated by models) ───────────────────────────────

export interface ImageOutputPart {
  type: 'image_output';
  mediaId: string;
  mimeType: string;
  revisedPrompt?: string;
  width?: number;
  height?: number;
  /** Transient: raw base64 from provider. Stripped after storage. */
  _data?: string;
}

export interface AudioOutputPart {
  type: 'audio_output';
  mediaId: string;
  mimeType: string;
  durationMs?: number;
  sampleRate?: number;
  _data?: string;
}

export interface VideoOutputPart {
  type: 'video_output';
  mediaId: string;
  mimeType: string;
  durationMs?: number;
  width?: number;
  height?: number;
  _data?: string;
}

export type MediaOutputPart = ImageOutputPart | AudioOutputPart | VideoOutputPart;

// ─── Data sources ──────────────────────────────────────────────────────────

export type DataSource =
  | { type: 'base64'; mimeType: string; data: string }
  | { type: 'url'; url: string }
  | { type: 'file'; fileId: string }
  | { type: 'path'; mimeType: string; path: string }
  | { type: 'buffer'; mimeType: string; data: Uint8Array }
  | { type: 'provider_ref'; mimeType: string; refId: string };

export type Content = string | ContentPart[];

export interface Message {
  role: Role;
  content: Content;
  cache?: boolean;
  /** Universal message id (ours) — for dedup / referencing / editing. */
  id?: string;
  /** Creation timestamp (ms epoch) — universal; drives server-state TTL checks. */
  createdAt?: number;
  /** Producer-bound provenance (assistant turns). See {@link MessageOrigin}. */
  origin?: MessageOrigin;
}

/** Normalize any content to ContentPart array. */
export function contentParts(content: Content): ContentPart[] {
  if (typeof content === 'string') return [{ type: 'text', text: content }];
  return content;
}

/** Extract plain text from content. */
export function contentText(content: Content): string {
  if (typeof content === 'string') return content;
  return content
    .filter((p): p is TextPart => p.type === 'text')
    .map((p) => p.text)
    .join('');
}
