/** Universal message and content types — shared by LLM, Agent, Server. */

import type { ProviderName } from './provider';

export type Role = 'system' | 'user' | 'assistant' | 'tool';

/** Producer-bound provenance for an assistant turn.
 *
 *  History is portable across providers, but some state is only valid for the
 *  provider that produced it: a server-side conversation id (interaction_id /
 *  response_id) and opaque signatures (Gemini thought-signatures, reasoning
 *  blobs). Anything here MUST be ignored by a different provider — adapters
 *  consume it only when `origin.provider === self`. */
export interface MessageOrigin {
  /** Provider that produced this assistant turn. The gate for cross-provider use. */
  provider: ProviderName;
  /** Model that produced it (for model-bound server-state checks). */
  model?: string;
  /** Server-side conversation id for stateful continuation (interaction_id / response_id). */
  serverStateId?: string;
  /** Opaque provider signatures to echo back (thought-signature, encrypted reasoning). */
  signatures?: unknown;
}

export type ContentPart =
  | TextPart
  | ImagePart
  | DocumentPart
  | AudioPart
  | VideoPart
  | ToolCallPart
  | ToolResultPart
  | ImageOutputPart
  | AudioOutputPart
  | VideoOutputPart;

/** Whether a piece of assistant text is the ANSWER or narration on the way to it.
 *
 *  `commentary` is the model thinking out loud for the user's benefit — distinct from reasoning,
 *  which is its own part. `final_answer` is the response proper. Codex-family models emit both, and
 *  without the distinction an agent loop treats narration as the result.
 *
 *  Open union (CONSTITUTION.md R1): a provider adding a third phase must not break consumers, so
 *  write a `default` branch. */
export type AssistantPhase = 'commentary' | 'final_answer' | (string & {});

export interface TextPart {
  type: 'text';
  text: string;
  cache?: boolean;
  /** Set only by providers that report it (OpenAI Responses, `gpt-5.3-codex` and later). Absent
   *  everywhere else, which reads exactly as it did before: treat the text as the answer. */
  phase?: AssistantPhase;
}

export interface ImagePart {
  type: 'image';
  source: DataSource;
  detail?: 'auto' | 'low' | 'high';
}

export interface DocumentPart {
  type: 'document';
  source: DataSource;
  citations?: boolean;
}

export interface AudioPart {
  type: 'audio';
  source: DataSource;
}

export interface VideoPart {
  type: 'video';
  source: DataSource;
}

export interface ToolCallPart {
  type: 'tool_call';
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  /** Provider-specific metadata (e.g. Google thought signatures). */
  _meta?: Record<string, unknown>;
}

export interface ToolResultPart {
  type: 'tool_result';
  id: string;
  content: string | ContentPart[];
  isError?: boolean;
  /** The namespace of the tool that produced this result, when the provider tracks one (OpenAI
   *  Responses). Round-tripped so a namespaced tool's output is attributable on the next turn; the
   *  tool NAME is derived from the matching call rather than stored twice. */
  namespace?: string;
}

// ─── Media Output Parts (generated by models) ───────────────────────────────

export interface ImageOutputPart {
  type: 'image_output';
  mediaId: string;
  mimeType: string;
  revisedPrompt?: string;
  width?: number;
  height?: number;
  /** Transient: raw base64 from provider. Stripped after storage. */
  _data?: string;
}

export interface AudioOutputPart {
  type: 'audio_output';
  mediaId: string;
  mimeType: string;
  durationMs?: number;
  sampleRate?: number;
  _data?: string;
}

export interface VideoOutputPart {
  type: 'video_output';
  mediaId: string;
  mimeType: string;
  durationMs?: number;
  width?: number;
  height?: number;
  _data?: string;
}

export type MediaOutputPart = ImageOutputPart | AudioOutputPart | VideoOutputPart;

// ─── Data sources ──────────────────────────────────────────────────────────

export type DataSource =
  | { type: 'base64'; mimeType: string; data: string }
  | { type: 'url'; url: string }
  | { type: 'file'; fileId: string }
  | { type: 'path'; mimeType: string; path: string }
  | { type: 'buffer'; mimeType: string; data: Uint8Array }
  | { type: 'provider_ref'; mimeType: string; refId: string };

export type Content = string | ContentPart[];

export interface Message {
  role: Role;
  content: Content;
  cache?: boolean;
  /** Universal message id (ours) — for dedup / referencing / editing. */
  id?: string;
  /** Creation timestamp (ms epoch) — universal; drives server-state TTL checks. */
  createdAt?: number;
  /** Producer-bound provenance (assistant turns). See {@link MessageOrigin}. */
  origin?: MessageOrigin;
}

/** Normalize any content to ContentPart array. */
export function contentParts(content: Content): ContentPart[] {
  if (typeof content === 'string') return [{ type: 'text', text: content }];
  return content;
}

/** Extract plain text from content. */
export function contentText(content: Content): string {
  if (typeof content === 'string') return content;
  return content
    .filter((p): p is TextPart => p.type === 'text')
    .map((p) => p.text)
    .join('');
}

/** The assistant's ANSWER, with commentary removed.
 *
 *  Codex-family models narrate before answering and mark the narration `phase: 'commentary'`.
 *  Concatenating everything makes an agent's final output include its own thinking-out-loud.
 *
 *  Excludes only what is explicitly `'commentary'` rather than keeping only `'final_answer'`: the
 *  phase vocabulary is open (R1), and a phase we do not recognise yet must never cause us to drop
 *  the answer. Text with no phase at all — every other model — is returned unchanged, so this is
 *  identical to `contentText` outside the codex family. */
export function finalAnswerText(content: Content): string {
  if (typeof content === 'string') return content;
  return content
    .filter((p): p is TextPart => p.type === 'text' && p.phase !== 'commentary')
    .map((p) => p.text)
    .join('');
}
