/** Universal completion response. */

import type { ContentPart, MediaOutputPart, ToolCallPart } from './messages';

export interface CompletionResponse {
  id: string;
  model: string;
  content: ContentPart[];
  finishReason: FinishReason;
  usage: Usage;

  // Convenience accessors (derived from content[]):
  text: string;
  toolCalls: ToolCallPart[];
  thinking: string | null;

  /** Media output parts (images, audio, video generated by model). */
  media: MediaOutputPart[];

  // Timing
  latencyMs: number;

  // Provider's raw response (escape hatch)
  raw: unknown;
}

export type FinishReason = 'stop' | 'tool_use' | 'length' | 'content_filter' | 'error';

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cachedTokens: number;
  cacheWriteTokens: number;
  reasoningTokens: number;
  /** Audio input/output tokens (realtime / audio models). When set, inputTokens/
   *  outputTokens count only the TEXT portion so cost prices each at its own rate. */
  audioInputTokens?: number;
  audioOutputTokens?: number;
  /** Service tier the provider actually billed, RAW as it reported it (openai
   *  `flex|priority|…`, anthropic `standard|priority|batch`). Auditable. */
  serviceTier?: string;
  /** The raw tier normalized by the adapter to the catalog's tier key — what cost
   *  uses for `pricing.tiers[...]`. Set alongside serviceTier; usually identical. */
  pricingTier?: string;
}

export function emptyUsage(): Usage {
  return {
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    cachedTokens: 0,
    cacheWriteTokens: 0,
    reasoningTokens: 0,
  };
}
