/** Universal completion response. */

import type { ModerationReport } from '../moderation/types';
import type { ContentPart, MediaOutputPart, ToolCallPart } from './messages';

export interface CompletionResponse {
  id: string;
  model: string;
  content: ContentPart[];
  finishReason: FinishReason;
  usage: Usage;

  // Convenience accessors (derived from content[]):
  text: string;
  toolCalls: ToolCallPart[];
  thinking: string | null;

  /** Media output parts (images, audio, video generated by model). */
  media: MediaOutputPart[];

  /** Files produced by hosted tools (e.g. code execution) - charts, data files,
   *  etc. Unified across providers. When only `id` is set, fetch the bytes via the
   *  provider's files API; some providers return `data` inline. Absent when none. */
  files?: FileOutput[];

  /** Hosted (provider-run) builtin tools the model invoked this turn — e.g. a web
   *  search or code-execution run. A durable trail of what was called (the provider
   *  ran them server-side; nothing for the client to execute). Absent when none. */
  builtinToolCalls?: BuiltinToolCall[];

  /** Sources the answer cited, unified across providers.
   *
   *  Distinct from `builtinToolCalls`, which records what the model INVOKED: a turn
   *  can run three searches and cite one page, or open a page and cite nothing.
   *  Rendering footnotes needs this list, not that one.
   *
   *  Absent when the model cited nothing — R3: a response type grows by OPTIONAL
   *  fields only, so this cannot be the always-present array the Python port
   *  exposes. Read it as `response.citations ?? []`. */
  citations?: Citation[];

  /** Inline-moderation outcome, when the `moderation` request option was used.
   *  Report-only: present for observability; it never blocks the call. Absent when
   *  moderation was not requested. */
  moderation?: ModerationReport;

  /** Why the turn failed, when `finishReason` is `'error'`. Some providers report a
   *  failure *inside* a 200 response instead of a transport error (OpenAI Responses
   *  `status: 'failed'` + `response.error`, Google Interactions `status: 'failed'`), so
   *  there is no exception to catch — without this the caller only sees an empty result.
   *  Absent unless the provider reported a failure. */
  error?: {
    /** Provider error code, e.g. OpenAI `data_residency_mismatch` (added 2026-07)
     *  or `misalignment_policy_violation` (added 2026-09). A number on the wire is
     *  read as its decimal string: OpenAI sends both, and openai-py 3.14 coerces
     *  the same way, so a numeric code is a code and not an absent one. */
    code?: string;
    message?: string;
    /** Present when a safety system blocked the turn AND explained itself
     *  (OpenAI `misalignment_policy_violation`, 2026-09). `message` says the turn
     *  was blocked; this says what about it looked wrong and, sometimes, what to
     *  send instead -- which is the difference between an agent that stops and
     *  one that can carry on. */
    misalignment?: {
      /** The public explanation for the block. */
      detailedExplanation?: string;
      /** Deliberately open: the provider documents four values and says clients
       *  must accept more. */
      errorType?:
        | 'potentially_unintended_data_transfer'
        | 'potentially_unintended_data_access'
        | 'potentially_unintended_destructive_activity'
        | 'other'
        | (string & {});
      /** A continuation instruction, when the provider offers one. */
      steer?: { message: string };
    };
  };

  /** Opaque provider state this turn produced that the NEXT request has to send
   *  back, verbatim. Never interpreted here, and never portable: an adapter
   *  consumes it only when it produced it.
   *
   *  Google Interactions is the case that forced it. A turn returns a `thought`
   *  step carrying nothing but a `signature`, which this library used to drop on
   *  the floor -- the buffered parse had no case for the step type, and the
   *  stream spec called the delta "internal". Measured 2026-09-29: echoing the
   *  step on the next turn is accepted, and echoing it with the signature
   *  corrupted is refused 400 "Corrupted thought signature", so the server reads
   *  it rather than tolerating it. Dropping it silently discards the model's own
   *  reasoning continuity.
   *
   *  `buildAssistantMessage` copies this onto `message.origin.signatures`, which
   *  is where an adapter reads it back. */
  signatures?: unknown;

  /** Why the prompt cache could not reuse the prefix of an earlier request, when
   *  `cacheDiagnostics` asked the provider to compare against one. Absent unless
   *  it was asked for and the provider had something to say. */
  cacheDiagnostics?: CacheDiagnostics;

  // Timing
  latencyMs: number;

  // Provider's raw response (escape hatch)
  raw: unknown;
}

/** What the provider reported about prompt-cache reuse against a named earlier
 *  request. Two providers, one concept, and the shapes were MEASURED on
 *  2026-09-29 rather than read out of their SDK types -- which would have got
 *  the most important case wrong.
 *
 *  **A hit is not reported the same way.** OpenAI answers `{type: 'cache_hit'}`.
 *  Anthropic has no hit variant at all: a request whose prefix WAS reused comes
 *  back with `diagnostics: null`, the same body an undiagnosed request gets. Its
 *  SDK documents that null as "diagnosis still pending", which is true and is not
 *  the whole truth. So `status: 'hit'` is only ever set from a provider that said
 *  so; on Anthropic the absence of this field is not evidence of a miss, and
 *  `usage.cachedTokens` is what answers "was the cache used". Inferring a hit
 *  from the token counts here would dress our arithmetic as the provider's
 *  answer.
 *
 *  `status` and `reason` are OPEN unions (R1): both providers have added values
 *  to these enums already, and a value we have not seen must reach the caller
 *  rather than be flattened into a neighbouring one. */
export interface CacheDiagnostics {
  /** `hit` | `miss` | `comparison_not_found` (the id named by `compareWith` is
   *  unknown or expired -- both providers answer 200, not an error) |
   *  `unavailable` (the provider declined to diagnose: too little to cache, or
   *  the feature is off for this account). Open union. */
  status: 'hit' | 'miss' | 'comparison_not_found' | 'unavailable' | (string & {});
  /** Present on a miss: what diverged. Anthropic reports the block that changed
   *  (`model_changed` | `system_changed` | `tools_changed` | `messages_changed`);
   *  OpenAI reports a finer set (`input_changed`, `reasoning_effort_changed`,
   *  `service_tier_changed`, ...). Open union -- the two vocabularies are NOT
   *  mapped onto each other, because a shared name would be a guess about which
   *  of the other's values it stands for. */
  reason?: string;
  /** Approximate input tokens that would have been read from cache had the
   *  prefix matched. Anthropic `cache_missed_input_tokens`, OpenAI
   *  `cache_missed_tokens`. */
  missedTokens?: number;
  /** OpenAI only: the reusable prefix length in the compared response
   *  (`comparison_reusable_tokens`). Anthropic does not report it. */
  reusableTokens?: number;
  /** The provider's own object, unflattened. */
  raw: unknown;
}

/** A file produced by a hosted tool (code execution output, etc.). */
export interface FileOutput {
  /** Provider file id, to fetch the bytes separately (e.g. Anthropic container
   *  file_id, OpenAI file_id). */
  id?: string;
  /** Filename, when the provider supplies one. */
  name?: string;
  /** MIME type, when known. */
  mimeType?: string;
  /** Inline bytes (base64) when the provider returns the file inline; else absent. */
  data?: string;
  /** URL to fetch the file when the provider returns one (e.g. OpenAI code-interpreter
   *  image outputs); else absent. */
  url?: string;
  /** What produced it (e.g. 'code_execution'). */
  source?: string;
  /** Provider-specific retrieval hints, used by `retrieveFile`/`streamFile` when the
   *  file is fetched by `id` (e.g. OpenAI container files set `{ containerId }`).
   *  Absent for providers that don't need extra context. */
  ref?: Record<string, unknown>;
}

/** A source the answer cited.
 *
 *  Four providers report these four different ways — Anthropic on the text block,
 *  Google in `groundingMetadata`, OpenAI as annotations, xAI as bare top-level URLs.
 *  The differences stop at the adapter. */
export interface Citation {
  url: string;
  /** Page title, when the provider supplies one. */
  title?: string;
  /** The passage the source supports. Only Anthropic reports this today; absent
   *  elsewhere rather than faked from the answer text. */
  text?: string;
}

/** A hosted builtin tool the model invoked (provider-run), with its inputs/outputs. */
export interface BuiltinToolCall {
  /** Unified tool name: `'web_search'` | `'code_interpreter'` | … (normalized from
   *  each provider's native name — e.g. Anthropic `code_execution`). */
  tool: string;
  /** Provider call id, when available (correlates the stream start/end events). */
  id?: string;
  /** `code_interpreter`: the code the model executed. */
  code?: string;
  /** `code_interpreter`: the code's textual output (stdout / logs). */
  output?: string;
  /** `web_search`: the query the model searched for (the first, if it issued several).
   *  Absent for page-open/read steps — see `url`. */
  query?: string;
  /** `web_search`: the URL the model opened/read (OpenAI/xAI `open_page`/`find`
   *  actions, which carry a URL instead of a query). Absent for plain searches. */
  url?: string;
  /** `web_search`: the URLs the search drew on, when the provider names them
   *  (OpenAI `action.sources[]`). The pages behind an answer, which is what a
   *  caller needs to show a citation list or audit where a claim came from. */
  sources?: string[];
  /** `web_search`: the results themselves, when the provider returned them.
   *
   *  OpenAI omits `web_search_call.results` unless the request asked for it,
   *  and the adapter asks whenever `search_content_types` includes `'image'`
   *  -- so image results arrive rather than being silently absent. The four
   *  documented image fields are normalised; anything else the provider sent
   *  is preserved alongside them rather than dropped. */
  results?: Array<{
    /** The image itself. */
    imageUrl?: string;
    /** The page the image was found on. */
    sourceWebsiteUrl?: string;
    /** A smaller preview, when one exists. */
    thumbnailUrl?: string;
    /** A short description, when `image_settings.caption` asked for one. */
    caption?: string;
    /** Whatever else this provider put on a result. */
    [key: string]: unknown;
  }>;
}

/** The finish reasons this SDK documents and maps deliberately. */
export type KnownFinishReason =
  | 'stop'
  | 'tool_use'
  | 'length'
  | 'content_filter'
  | 'error'
  | 'pending'
  /** The model tried to call a tool and produced something unusable — malformed arguments, a
   *  hallucinated tool name, a truncated call. Distinct from `error` (the request itself failed)
   *  and from `tool_use` (a call we can execute): this turn is *recoverable* by telling the model
   *  what went wrong and letting it try again — see `reflectAndRetry` on `AgentLoop`. */
  | 'malformed_tool_call';

/** Why a turn ended.
 *
 *  **This union is OPEN by design** (CONSTITUTION.md R1). Providers keep inventing terminal states —
 *  four of them did so in a single upstream cycle — and against a closed union every one of those is
 *  a breaking change for every consumer, including consumers of providers that changed nothing.
 *  Always write a `default` branch; use `KnownFinishReason` where you want the documented set alone.
 *
 *  `pending` is NOT terminal: the provider accepted the request but has not produced a completion
 *  yet, so the response carries no content. It exists because several providers can return a
 *  non-terminal status on an otherwise successful call — Google Interactions `queued` (google 2.13)
 *  and OpenAI Responses `queued` / `in_progress` (background mode). Those used to fall through to
 *  `stop`, which claimed a clean finish for an empty response. Treat `pending` as "poll/retry",
 *  never as a result. */
export type FinishReason = KnownFinishReason | (string & {});

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cachedTokens: number;
  cacheWriteTokens: number;
  reasoningTokens: number;
  /** Audio input/output tokens (realtime / audio models). When set, inputTokens/
   *  outputTokens count only the TEXT portion so cost prices each at its own rate. */
  audioInputTokens?: number;
  audioOutputTokens?: number;
  /** Service tier the provider actually billed, RAW as it reported it (openai
   *  `flex|priority|…`, anthropic `standard|priority|batch`). Auditable. */
  serviceTier?: string;
  /** The raw tier normalized by the adapter to the catalog's tier key — what cost
   *  uses for `pricing.tiers[...]`. Set alongside serviceTier; usually identical. */
  pricingTier?: string;
}

export function emptyUsage(): Usage {
  return {
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    cachedTokens: 0,
    cacheWriteTokens: 0,
    reasoningTokens: 0,
  };
}
