/** Every wire spec the SDK ships, indexed by id.
 *
 *  A spec says HOW to talk to a provider API: field names, enum values, defaults,
 *  which shape a model version takes. It is deliberately DATA, so the same file
 *  is consumed by this SDK and by the Python and Rust ports, and a provider
 *  change is one reviewable diff rather than three code changes.
 *
 *  GENERATED by scripts/gen-wire-registry.ts — do not hand-edit. Add a spec by
 *  dropping the JSON into src/wire/specs/ and running `bun run gen:registry`.
 *
 *  This index is what the chain tests and the coverage audit enumerate. The
 *  ADAPTERS do not read it: each family has its own loader (chat-specs,
 *  media-specs, service-specs, retrieval-specs) so a chat call does not drag
 *  every batch and media spec into the bundle.
 */

import type { SpecDelta } from './inherit';

import spec_anthropic_batch_base from './specs/batch/anthropic.base.json';
import spec_anthropic_batch_cancel from './specs/batch/anthropic.cancel.json';
import spec_anthropic_batch_getResults from './specs/batch/anthropic.getResults.json';
import spec_anthropic_batch_getStatus from './specs/batch/anthropic.getStatus.json';
import spec_anthropic_batch_submit from './specs/batch/anthropic.submit.json';
import spec_anthropic_count_messages from './specs/count/anthropic.json';
import spec_anthropic_files_base from './specs/files/anthropic.base.json';
import spec_anthropic_files_content from './specs/files/anthropic.content.json';
import spec_anthropic_files_delete from './specs/files/anthropic.delete.json';
import spec_anthropic_files_getInfo from './specs/files/anthropic.getInfo.json';
import spec_anthropic_files_list from './specs/files/anthropic.list.json';
import spec_anthropic_files_upload from './specs/files/anthropic.upload.json';
import spec_anthropic_messages_4_0 from './specs/anthropic-chain/messages@4.0.json';
import spec_anthropic_messages_4_1 from './specs/anthropic-chain/messages@4.1.json';
import spec_anthropic_messages_4_6 from './specs/anthropic-chain/messages@4.6.json';
import spec_anthropic_messages_4_7 from './specs/anthropic-chain/messages@4.7.json';
import spec_anthropic_models_list from './specs/models/anthropic.json';
import spec_files_download_byUrl from './specs/files/download.byUrl.json';
import spec_google_batch_cancel from './specs/batch/google.cancel.json';
import spec_google_batch_getResults from './specs/batch/google.getResults.json';
import spec_google_batch_getStatus from './specs/batch/google.getStatus.json';
import spec_google_batch_submit from './specs/batch/google.submit.json';
import spec_google_count_tokens from './specs/count/google.json';
import spec_google_embeddings from './specs/embeddings/google.json';
import spec_google_files_content from './specs/files/google.content.json';
import spec_google_files_delete from './specs/files/google.delete.json';
import spec_google_files_finishUpload from './specs/files/google.finishUpload.json';
import spec_google_files_getInfo from './specs/files/google.getInfo.json';
import spec_google_files_list from './specs/files/google.list.json';
import spec_google_files_startUpload from './specs/files/google.startUpload.json';
import spec_google_gemini_image_edit_generateContent from './specs/google-media/gemini-image-edit.json';
import spec_google_gemini_image_generateContent from './specs/google-media/gemini-image.json';
import spec_google_gemini_tts_generateContent from './specs/google-media/gemini-tts.json';
import spec_google_generate_2_5 from './specs/google-chain/generate@2.5.json';
import spec_google_generate_3 from './specs/google-chain/generate@3.json';
import spec_google_imagen_predict from './specs/google-media/imagen.json';
import spec_google_interactions from './specs/google-interactions.json';
import spec_google_media_download from './specs/google-media/download.json';
import spec_google_media_generateContent from './specs/google-media/generateContent.base.json';
import spec_google_media_operation_cancel from './specs/google-media/operation.cancel.json';
import spec_google_media_operation_status from './specs/google-media/operation.status.json';
import spec_google_media_predict from './specs/google-media/predict.base.json';
import spec_google_models_list from './specs/models/google.json';
import spec_google_realtime from './specs/realtime/google.json';
import spec_google_retrieval_base from './specs/retrieval/google.base.json';
import spec_google_retrieval_createCorpus from './specs/retrieval/google.createCorpus.json';
import spec_google_retrieval_deleteCorpus from './specs/retrieval/google.deleteCorpus.json';
import spec_google_retrieval_importFile from './specs/retrieval/google.importFile.json';
import spec_google_retrieval_indexStatus from './specs/retrieval/google.indexStatus.json';
import spec_google_retrieval_json from './specs/retrieval/google.jsonBase.json';
import spec_google_retrieval_listCorpora from './specs/retrieval/google.listCorpora.json';
import spec_google_retrieval_pollOperation from './specs/retrieval/google.pollOperation.json';
import spec_google_retrieval_removeDocument from './specs/retrieval/google.removeDocument.json';
import spec_google_retrieval_uploadFile from './specs/retrieval/google.uploadFile.json';
import spec_google_veo_predictLongRunning from './specs/google-media/veo.json';
import spec_mcp_oauth_authorize from './specs/mcp-oauth/authorize.json';
import spec_mcp_oauth_base from './specs/mcp-oauth/base.json';
import spec_mcp_oauth_discover_oauth from './specs/mcp-oauth/discover.oauth.json';
import spec_mcp_oauth_discover_oidc from './specs/mcp-oauth/discover.oidc.json';
import spec_mcp_oauth_register from './specs/mcp-oauth/register.json';
import spec_mcp_oauth_token_exchange from './specs/mcp-oauth/token.exchange.json';
import spec_mcp_oauth_token_refresh from './specs/mcp-oauth/token.refresh.json';
import spec_mcp_http_base from './specs/mcp/http.base.json';
import spec_mcp_http_close from './specs/mcp/http.close.json';
import spec_mcp_http_events from './specs/mcp/http.events.json';
import spec_mcp_http_longLived from './specs/mcp/http.longLived.json';
import spec_mcp_http_message from './specs/mcp/http.message.json';
import spec_mcp_http_notify from './specs/mcp/http.notify.json';
import spec_mcp_http_request from './specs/mcp/http.request.json';
import spec_openai_audio_speech from './specs/openai-media/audio.speech.json';
import spec_openai_batch_base from './specs/batch/openai.base.json';
import spec_openai_batch_cancel from './specs/batch/openai.cancel.json';
import spec_openai_batch_create from './specs/batch/openai.create.json';
import spec_openai_batch_getResults from './specs/batch/openai.getResults.json';
import spec_openai_batch_getStatus from './specs/batch/openai.getStatus.json';
import spec_openai_batch_uploadJsonl from './specs/batch/openai.uploadJsonl.json';
import spec_openai_chat_completions from './specs/openai-completions.json';
import spec_openai_embeddings from './specs/embeddings/openai.json';
import spec_openai_files_base from './specs/files/openai.base.json';
import spec_openai_files_content from './specs/files/openai.content.json';
import spec_openai_files_content_container from './specs/files/openai.content.container.json';
import spec_openai_files_delete from './specs/files/openai.delete.json';
import spec_openai_files_getInfo from './specs/files/openai.getInfo.json';
import spec_openai_files_list from './specs/files/openai.list.json';
import spec_openai_files_upload from './specs/files/openai.upload.json';
import spec_openai_images_edits from './specs/openai-media/images.edits.json';
import spec_openai_images_generations from './specs/openai-media/images.generations.json';
import spec_openai_images_generations_dall_e from './specs/openai-media/images.generations.dalle.json';
import spec_openai_media_base from './specs/openai-media/media.base.json';
import spec_openai_media_images from './specs/openai-media/images.base.json';
import spec_openai_models_list from './specs/models/openai.json';
import spec_openai_moderations from './specs/moderation/openai.json';
import spec_openai_provenance_check from './specs/provenance/openai.json';
import spec_openai_realtime from './specs/realtime/openai.json';
import spec_openai_responses from './specs/openai-responses.json';
import spec_openai_retrieval_attachDocument from './specs/retrieval/openai.attachDocument.json';
import spec_openai_retrieval_base from './specs/retrieval/openai.base.json';
import spec_openai_retrieval_createCorpus from './specs/retrieval/openai.createCorpus.json';
import spec_openai_retrieval_deleteCorpus from './specs/retrieval/openai.deleteCorpus.json';
import spec_openai_retrieval_indexStatus from './specs/retrieval/openai.indexStatus.json';
import spec_openai_retrieval_json from './specs/retrieval/openai.jsonBase.json';
import spec_openai_retrieval_listCorpora from './specs/retrieval/openai.listCorpora.json';
import spec_openai_retrieval_removeDocument from './specs/retrieval/openai.removeDocument.json';
import spec_openai_retrieval_uploadFile from './specs/retrieval/openai.uploadFile.json';
import spec_openai_transcriptions from './specs/transcription/openai.json';
import spec_openai_videos from './specs/openai-media/videos.json';
import spec_openai_videos_content from './specs/openai-media/videos.content.json';
import spec_openai_videos_status from './specs/openai-media/videos.status.json';
import spec_openrouter_embeddings from './specs/embeddings/openrouter.json';
import spec_openrouter_media_audio from './specs/openrouter-media/audio.json';
import spec_openrouter_media_base from './specs/openrouter-media/base.json';
import spec_openrouter_media_image from './specs/openrouter-media/image.json';
import spec_openrouter_media_imageEdit from './specs/openrouter-media/image.edit.json';
import spec_openrouter_models_list from './specs/models/openrouter.json';
import spec_xai_batch_addRequests from './specs/batch/xai.addRequests.json';
import spec_xai_batch_base from './specs/batch/xai.base.json';
import spec_xai_batch_cancel from './specs/batch/xai.cancel.json';
import spec_xai_batch_create from './specs/batch/xai.create.json';
import spec_xai_batch_getResults from './specs/batch/xai.getResults.json';
import spec_xai_batch_getStatus from './specs/batch/xai.getStatus.json';
import spec_xai_count_tokenize from './specs/count/xai.json';
import spec_xai_files_upload from './specs/files/xai.upload.json';
import spec_xai_images_base from './specs/xai-media/images.base.json';
import spec_xai_images_edits from './specs/xai-media/images.edits.json';
import spec_xai_images_generations from './specs/xai-media/images.generations.json';
import spec_xai_media_base from './specs/xai-media/base.json';
import spec_xai_media_download from './specs/xai-media/download.json';
import spec_xai_models_list from './specs/models/xai.json';
import spec_xai_retrieval_attachDocument from './specs/retrieval/xai.attachDocument.json';
import spec_xai_retrieval_base from './specs/retrieval/xai.base.json';
import spec_xai_retrieval_createCorpus from './specs/retrieval/xai.createCorpus.json';
import spec_xai_retrieval_deleteCorpus from './specs/retrieval/xai.deleteCorpus.json';
import spec_xai_retrieval_indexStatus from './specs/retrieval/xai.indexStatus.json';
import spec_xai_retrieval_listCorpora from './specs/retrieval/xai.listCorpora.json';
import spec_xai_retrieval_listDocuments from './specs/retrieval/xai.listDocuments.json';
import spec_xai_retrieval_management from './specs/retrieval/xai.management.json';
import spec_xai_retrieval_removeDocument from './specs/retrieval/xai.removeDocument.json';
import spec_xai_retrieval_search from './specs/retrieval/xai.search.json';
import spec_xai_retrieval_standard from './specs/retrieval/xai.standard.json';
import spec_xai_retrieval_standardJson from './specs/retrieval/xai.standardJson.json';
import spec_xai_retrieval_uploadFile from './specs/retrieval/xai.uploadFile.json';
import spec_xai_tts from './specs/xai-media/tts.json';
import spec_xai_videos_cancel from './specs/xai-media/videos.cancel.json';
import spec_xai_videos_edits from './specs/xai-media/videos.edits.json';
import spec_xai_videos_extensions from './specs/xai-media/videos.extensions.json';
import spec_xai_videos_generations from './specs/xai-media/videos.generations.json';
import spec_xai_videos_status from './specs/xai-media/videos.status.json';

/** All shipped specs, keyed by `provider/api@version` id. */
export const WIRE_SPECS: ReadonlyMap<string, SpecDelta> = new Map<string, SpecDelta>([
  ['anthropic/batch.base', spec_anthropic_batch_base as unknown as SpecDelta],
  ['anthropic/batch.cancel', spec_anthropic_batch_cancel as unknown as SpecDelta],
  ['anthropic/batch.getResults', spec_anthropic_batch_getResults as unknown as SpecDelta],
  ['anthropic/batch.getStatus', spec_anthropic_batch_getStatus as unknown as SpecDelta],
  ['anthropic/batch.submit', spec_anthropic_batch_submit as unknown as SpecDelta],
  ['anthropic/count.messages', spec_anthropic_count_messages as unknown as SpecDelta],
  ['anthropic/files.base', spec_anthropic_files_base as unknown as SpecDelta],
  ['anthropic/files.content', spec_anthropic_files_content as unknown as SpecDelta],
  ['anthropic/files.delete', spec_anthropic_files_delete as unknown as SpecDelta],
  ['anthropic/files.getInfo', spec_anthropic_files_getInfo as unknown as SpecDelta],
  ['anthropic/files.list', spec_anthropic_files_list as unknown as SpecDelta],
  ['anthropic/files.upload', spec_anthropic_files_upload as unknown as SpecDelta],
  ['anthropic/messages@4.0', spec_anthropic_messages_4_0 as unknown as SpecDelta],
  ['anthropic/messages@4.1', spec_anthropic_messages_4_1 as unknown as SpecDelta],
  ['anthropic/messages@4.6', spec_anthropic_messages_4_6 as unknown as SpecDelta],
  ['anthropic/messages@4.7', spec_anthropic_messages_4_7 as unknown as SpecDelta],
  ['anthropic/models.list', spec_anthropic_models_list as unknown as SpecDelta],
  ['files/download.byUrl', spec_files_download_byUrl as unknown as SpecDelta],
  ['google/batch.cancel', spec_google_batch_cancel as unknown as SpecDelta],
  ['google/batch.getResults', spec_google_batch_getResults as unknown as SpecDelta],
  ['google/batch.getStatus', spec_google_batch_getStatus as unknown as SpecDelta],
  ['google/batch.submit', spec_google_batch_submit as unknown as SpecDelta],
  ['google/count.tokens', spec_google_count_tokens as unknown as SpecDelta],
  ['google/embeddings', spec_google_embeddings as unknown as SpecDelta],
  ['google/files.content', spec_google_files_content as unknown as SpecDelta],
  ['google/files.delete', spec_google_files_delete as unknown as SpecDelta],
  ['google/files.finishUpload', spec_google_files_finishUpload as unknown as SpecDelta],
  ['google/files.getInfo', spec_google_files_getInfo as unknown as SpecDelta],
  ['google/files.list', spec_google_files_list as unknown as SpecDelta],
  ['google/files.startUpload', spec_google_files_startUpload as unknown as SpecDelta],
  ['google/gemini-image-edit@generateContent', spec_google_gemini_image_edit_generateContent as unknown as SpecDelta],
  ['google/gemini-image@generateContent', spec_google_gemini_image_generateContent as unknown as SpecDelta],
  ['google/gemini-tts@generateContent', spec_google_gemini_tts_generateContent as unknown as SpecDelta],
  ['google/generate@2.5', spec_google_generate_2_5 as unknown as SpecDelta],
  ['google/generate@3', spec_google_generate_3 as unknown as SpecDelta],
  ['google/imagen@predict', spec_google_imagen_predict as unknown as SpecDelta],
  ['google/interactions', spec_google_interactions as unknown as SpecDelta],
  ['google/media.download', spec_google_media_download as unknown as SpecDelta],
  ['google/media.generateContent', spec_google_media_generateContent as unknown as SpecDelta],
  ['google/media.operation.cancel', spec_google_media_operation_cancel as unknown as SpecDelta],
  ['google/media.operation.status', spec_google_media_operation_status as unknown as SpecDelta],
  ['google/media.predict', spec_google_media_predict as unknown as SpecDelta],
  ['google/models.list', spec_google_models_list as unknown as SpecDelta],
  ['google/realtime', spec_google_realtime as unknown as SpecDelta],
  ['google/retrieval.base', spec_google_retrieval_base as unknown as SpecDelta],
  ['google/retrieval.createCorpus', spec_google_retrieval_createCorpus as unknown as SpecDelta],
  ['google/retrieval.deleteCorpus', spec_google_retrieval_deleteCorpus as unknown as SpecDelta],
  ['google/retrieval.importFile', spec_google_retrieval_importFile as unknown as SpecDelta],
  ['google/retrieval.indexStatus', spec_google_retrieval_indexStatus as unknown as SpecDelta],
  ['google/retrieval.json', spec_google_retrieval_json as unknown as SpecDelta],
  ['google/retrieval.listCorpora', spec_google_retrieval_listCorpora as unknown as SpecDelta],
  ['google/retrieval.pollOperation', spec_google_retrieval_pollOperation as unknown as SpecDelta],
  ['google/retrieval.removeDocument', spec_google_retrieval_removeDocument as unknown as SpecDelta],
  ['google/retrieval.uploadFile', spec_google_retrieval_uploadFile as unknown as SpecDelta],
  ['google/veo@predictLongRunning', spec_google_veo_predictLongRunning as unknown as SpecDelta],
  ['mcp-oauth/authorize', spec_mcp_oauth_authorize as unknown as SpecDelta],
  ['mcp-oauth/base', spec_mcp_oauth_base as unknown as SpecDelta],
  ['mcp-oauth/discover.oauth', spec_mcp_oauth_discover_oauth as unknown as SpecDelta],
  ['mcp-oauth/discover.oidc', spec_mcp_oauth_discover_oidc as unknown as SpecDelta],
  ['mcp-oauth/register', spec_mcp_oauth_register as unknown as SpecDelta],
  ['mcp-oauth/token.exchange', spec_mcp_oauth_token_exchange as unknown as SpecDelta],
  ['mcp-oauth/token.refresh', spec_mcp_oauth_token_refresh as unknown as SpecDelta],
  ['mcp/http.base', spec_mcp_http_base as unknown as SpecDelta],
  ['mcp/http.close', spec_mcp_http_close as unknown as SpecDelta],
  ['mcp/http.events', spec_mcp_http_events as unknown as SpecDelta],
  ['mcp/http.longLived', spec_mcp_http_longLived as unknown as SpecDelta],
  ['mcp/http.message', spec_mcp_http_message as unknown as SpecDelta],
  ['mcp/http.notify', spec_mcp_http_notify as unknown as SpecDelta],
  ['mcp/http.request', spec_mcp_http_request as unknown as SpecDelta],
  ['openai/audio.speech', spec_openai_audio_speech as unknown as SpecDelta],
  ['openai/batch.base', spec_openai_batch_base as unknown as SpecDelta],
  ['openai/batch.cancel', spec_openai_batch_cancel as unknown as SpecDelta],
  ['openai/batch.create', spec_openai_batch_create as unknown as SpecDelta],
  ['openai/batch.getResults', spec_openai_batch_getResults as unknown as SpecDelta],
  ['openai/batch.getStatus', spec_openai_batch_getStatus as unknown as SpecDelta],
  ['openai/batch.uploadJsonl', spec_openai_batch_uploadJsonl as unknown as SpecDelta],
  ['openai/chat-completions', spec_openai_chat_completions as unknown as SpecDelta],
  ['openai/embeddings', spec_openai_embeddings as unknown as SpecDelta],
  ['openai/files.base', spec_openai_files_base as unknown as SpecDelta],
  ['openai/files.content', spec_openai_files_content as unknown as SpecDelta],
  ['openai/files.content.container', spec_openai_files_content_container as unknown as SpecDelta],
  ['openai/files.delete', spec_openai_files_delete as unknown as SpecDelta],
  ['openai/files.getInfo', spec_openai_files_getInfo as unknown as SpecDelta],
  ['openai/files.list', spec_openai_files_list as unknown as SpecDelta],
  ['openai/files.upload', spec_openai_files_upload as unknown as SpecDelta],
  ['openai/images.edits', spec_openai_images_edits as unknown as SpecDelta],
  ['openai/images.generations', spec_openai_images_generations as unknown as SpecDelta],
  ['openai/images.generations@dall-e', spec_openai_images_generations_dall_e as unknown as SpecDelta],
  ['openai/media.base', spec_openai_media_base as unknown as SpecDelta],
  ['openai/media.images', spec_openai_media_images as unknown as SpecDelta],
  ['openai/models.list', spec_openai_models_list as unknown as SpecDelta],
  ['openai/moderations', spec_openai_moderations as unknown as SpecDelta],
  ['openai/provenance.check', spec_openai_provenance_check as unknown as SpecDelta],
  ['openai/realtime', spec_openai_realtime as unknown as SpecDelta],
  ['openai/responses', spec_openai_responses as unknown as SpecDelta],
  ['openai/retrieval.attachDocument', spec_openai_retrieval_attachDocument as unknown as SpecDelta],
  ['openai/retrieval.base', spec_openai_retrieval_base as unknown as SpecDelta],
  ['openai/retrieval.createCorpus', spec_openai_retrieval_createCorpus as unknown as SpecDelta],
  ['openai/retrieval.deleteCorpus', spec_openai_retrieval_deleteCorpus as unknown as SpecDelta],
  ['openai/retrieval.indexStatus', spec_openai_retrieval_indexStatus as unknown as SpecDelta],
  ['openai/retrieval.json', spec_openai_retrieval_json as unknown as SpecDelta],
  ['openai/retrieval.listCorpora', spec_openai_retrieval_listCorpora as unknown as SpecDelta],
  ['openai/retrieval.removeDocument', spec_openai_retrieval_removeDocument as unknown as SpecDelta],
  ['openai/retrieval.uploadFile', spec_openai_retrieval_uploadFile as unknown as SpecDelta],
  ['openai/transcriptions', spec_openai_transcriptions as unknown as SpecDelta],
  ['openai/videos', spec_openai_videos as unknown as SpecDelta],
  ['openai/videos.content', spec_openai_videos_content as unknown as SpecDelta],
  ['openai/videos.status', spec_openai_videos_status as unknown as SpecDelta],
  ['openrouter/embeddings', spec_openrouter_embeddings as unknown as SpecDelta],
  ['openrouter/media.audio', spec_openrouter_media_audio as unknown as SpecDelta],
  ['openrouter/media.base', spec_openrouter_media_base as unknown as SpecDelta],
  ['openrouter/media.image', spec_openrouter_media_image as unknown as SpecDelta],
  ['openrouter/media.imageEdit', spec_openrouter_media_imageEdit as unknown as SpecDelta],
  ['openrouter/models.list', spec_openrouter_models_list as unknown as SpecDelta],
  ['xai/batch.addRequests', spec_xai_batch_addRequests as unknown as SpecDelta],
  ['xai/batch.base', spec_xai_batch_base as unknown as SpecDelta],
  ['xai/batch.cancel', spec_xai_batch_cancel as unknown as SpecDelta],
  ['xai/batch.create', spec_xai_batch_create as unknown as SpecDelta],
  ['xai/batch.getResults', spec_xai_batch_getResults as unknown as SpecDelta],
  ['xai/batch.getStatus', spec_xai_batch_getStatus as unknown as SpecDelta],
  ['xai/count.tokenize', spec_xai_count_tokenize as unknown as SpecDelta],
  ['xai/files.upload', spec_xai_files_upload as unknown as SpecDelta],
  ['xai/images.base', spec_xai_images_base as unknown as SpecDelta],
  ['xai/images.edits', spec_xai_images_edits as unknown as SpecDelta],
  ['xai/images.generations', spec_xai_images_generations as unknown as SpecDelta],
  ['xai/media.base', spec_xai_media_base as unknown as SpecDelta],
  ['xai/media.download', spec_xai_media_download as unknown as SpecDelta],
  ['xai/models.list', spec_xai_models_list as unknown as SpecDelta],
  ['xai/retrieval.attachDocument', spec_xai_retrieval_attachDocument as unknown as SpecDelta],
  ['xai/retrieval.base', spec_xai_retrieval_base as unknown as SpecDelta],
  ['xai/retrieval.createCorpus', spec_xai_retrieval_createCorpus as unknown as SpecDelta],
  ['xai/retrieval.deleteCorpus', spec_xai_retrieval_deleteCorpus as unknown as SpecDelta],
  ['xai/retrieval.indexStatus', spec_xai_retrieval_indexStatus as unknown as SpecDelta],
  ['xai/retrieval.listCorpora', spec_xai_retrieval_listCorpora as unknown as SpecDelta],
  ['xai/retrieval.listDocuments', spec_xai_retrieval_listDocuments as unknown as SpecDelta],
  ['xai/retrieval.management', spec_xai_retrieval_management as unknown as SpecDelta],
  ['xai/retrieval.removeDocument', spec_xai_retrieval_removeDocument as unknown as SpecDelta],
  ['xai/retrieval.search', spec_xai_retrieval_search as unknown as SpecDelta],
  ['xai/retrieval.standard', spec_xai_retrieval_standard as unknown as SpecDelta],
  ['xai/retrieval.standardJson', spec_xai_retrieval_standardJson as unknown as SpecDelta],
  ['xai/retrieval.uploadFile', spec_xai_retrieval_uploadFile as unknown as SpecDelta],
  ['xai/tts', spec_xai_tts as unknown as SpecDelta],
  ['xai/videos.cancel', spec_xai_videos_cancel as unknown as SpecDelta],
  ['xai/videos.edits', spec_xai_videos_edits as unknown as SpecDelta],
  ['xai/videos.extensions', spec_xai_videos_extensions as unknown as SpecDelta],
  ['xai/videos.generations', spec_xai_videos_generations as unknown as SpecDelta],
  ['xai/videos.status', spec_xai_videos_status as unknown as SpecDelta],
]);

/** Resolve a spec id to its flattened form, walking `extends`. */
export function getWireSpec(id: string): SpecDelta {
  const spec = WIRE_SPECS.get(id);
  if (!spec) throw new Error(`unknown wire spec: ${id}`);
  return spec;
}
