/** Regenerate `src/wire/registry.ts` from the spec files on disk.
 *
 *  The registry is a mechanical index of `src/wire/specs/**`, and it was being
 *  maintained by hand. Three times now a new spec landed without its registry
 *  entry, which does not fail loudly: the spec is simply invisible to
 *  `WIRE_SPECS`, so the chain tests skip it and the coverage audit reports it as
 *  neither referenced nor executed — the two checks that exist to catch exactly
 *  that. A generated file cannot fall behind the directory it indexes.
 *
 *  Run: bun run scripts/gen-wire-registry.ts   (or `bun run gen:registry`)
 *  `--check` verifies the file is current without writing, for CI.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const SPEC_ROOT = resolve(import.meta.dir, '../src/wire/specs');
const OUT = resolve(import.meta.dir, '../src/wire/registry.ts');

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (entry.name.endsWith('.json')) out.push(p);
  }
  return out;
}

/** A stable, collision-free identifier derived from the spec id itself, so two
 *  specs in different folders can never share one. */
const symbolFor = (id: string): string => `spec_${id.replace(/[^A-Za-z0-9]/g, '_')}`;

const files = walk(SPEC_ROOT).sort();
const entries = files.map((file) => {
  const spec = JSON.parse(readFileSync(file, 'utf8')) as { id?: string };
  if (!spec.id) throw new Error(`${file}: spec has no id`);
  const rel = `./specs/${relative(SPEC_ROOT, file).replace(/\\/g, '/')}`;
  return { id: spec.id, symbol: symbolFor(spec.id), rel };
});

const dupes = entries
  .map((e) => e.id)
  .filter((id, i, all) => all.indexOf(id) !== i);
if (dupes.length) throw new Error(`duplicate spec ids: ${[...new Set(dupes)].join(', ')}`);

const byId = [...entries].sort((a, b) => a.id.localeCompare(b.id));

const source = `/** Every wire spec the SDK ships, indexed by id.
 *
 *  A spec says HOW to talk to a provider API: field names, enum values, defaults,
 *  which shape a model version takes. It is deliberately DATA, so the same file
 *  is consumed by this SDK and by the Python and Rust ports, and a provider
 *  change is one reviewable diff rather than three code changes.
 *
 *  GENERATED by scripts/gen-wire-registry.ts — do not hand-edit. Add a spec by
 *  dropping the JSON into src/wire/specs/ and running \`bun run gen:registry\`.
 *
 *  This index is what the chain tests and the coverage audit enumerate. The
 *  ADAPTERS do not read it: each family has its own loader (chat-specs,
 *  media-specs, service-specs, retrieval-specs) so a chat call does not drag
 *  every batch and media spec into the bundle.
 */

import type { SpecDelta } from './inherit';

${byId.map((e) => `import ${e.symbol} from '${e.rel}';`).join('\n')}

/** All shipped specs, keyed by \`provider/api@version\` id. */
export const WIRE_SPECS: ReadonlyMap<string, SpecDelta> = new Map<string, SpecDelta>([
${byId.map((e) => `  ['${e.id}', ${e.symbol} as unknown as SpecDelta],`).join('\n')}
]);

/** Resolve a spec id to its flattened form, walking \`extends\`. */
export function getWireSpec(id: string): SpecDelta {
  const spec = WIRE_SPECS.get(id);
  if (!spec) throw new Error(\`unknown wire spec: \${id}\`);
  return spec;
}
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf8');
  if (current !== source) {
    console.error(`registry.ts is stale — run \`bun run gen:registry\` (${byId.length} specs on disk)`);
    process.exit(1);
  }
  console.log(`registry.ts is current (${byId.length} specs)`);
} else {
  writeFileSync(OUT, source);
  console.log(`registry.ts regenerated: ${byId.length} specs`);
}
